import type { ClarityNode, Project } from '@/types/clarity';
import type { DurableMemory } from '@/types/contextPack';
import { calculateClarityScore, selectTopGap } from '@/lib/prioritization';

export const HACKATHON_DEMO_ID = 'hackathon_harborhelp_demo';
export const HACKATHON_DEMO_CREATED_AT = '2026-08-16T10:00:00.000Z';

function node(params: Omit<ClarityNode, 'created_by' | 'created_at' | 'updated_at'>): ClarityNode {
  return {
    ...params,
    created_by: 'agent',
    created_at: HACKATHON_DEMO_CREATED_AT,
    updated_at: HACKATHON_DEMO_CREATED_AT,
  };
}

export function createHackathonDemoMemories(): DurableMemory[] {
  return [
    {
      id: 'hackathon_demo_team',
      category: 'current_priorities',
      text: 'Our three-person team can spend ten focused days on the hackathon build.',
      source: 'seed',
      source_refs: ['hackathon_team_notes'],
      confidence: 0.95,
      created_at: HACKATHON_DEMO_CREATED_AT,
      updated_at: HACKATHON_DEMO_CREATED_AT,
      why_remembered: 'Seeded by the repeatable HarborHelp hackathon demo.',
    },
    {
      id: 'hackathon_demo_quality_bar',
      category: 'current_priorities',
      text: 'The demo should prove a useful end-to-end workflow instead of showing a collection of disconnected features.',
      source: 'seed',
      source_refs: ['hackathon_judging_rubric'],
      confidence: 0.9,
      created_at: HACKATHON_DEMO_CREATED_AT,
      updated_at: HACKATHON_DEMO_CREATED_AT,
      why_remembered: 'Seeded by the judging rubric for the hackathon demo.',
    },
  ];
}

export function createHackathonDemoProject(): Project {
  const project: Project = {
    id: HACKATHON_DEMO_ID,
    title: 'HarborHelp — Community Food Rescue',
    goal: 'Build and validate a volunteer coordination tool that moves surplus food to nearby shelters within ten days.',
    status: 'active',
    deadline: '2026-08-26',
    one_sentence_context: 'A ten-day hackathon build for matching same-day surplus food with shelters, volunteers, and safe pickup windows.',
    clarity_score: 0,
    created_at: HACKATHON_DEMO_CREATED_AT,
    updated_at: HACKATHON_DEMO_CREATED_AT,
    sources: [
      {
        id: 'hackathon_brief',
        filename: 'harborhelp-hackathon-brief.pdf',
        type: 'pdf',
        content: 'HarborHelp should help a restaurant post surplus food, let a nearby shelter claim it, and coordinate a volunteer pickup before the food expires. The core demo must complete one request from posting to confirmed delivery.',
        extracted_at: HACKATHON_DEMO_CREATED_AT,
        derived_node_ids: ['harborhelp_goal', 'harborhelp_core_workflow', 'harborhelp_expiry_risk'],
        processing_status: 'completed',
        mime_type: 'application/pdf',
        origin: 'user',
        extraction_summary: 'The judging story is a same-day food rescue from restaurant post to shelter delivery.',
      },
      {
        id: 'hackathon_team_notes',
        filename: 'team-notes.md',
        type: 'note',
        content: 'The team has three people and ten focused build days. One person can own the mobile-friendly web flow, one can own matching and notifications, and one can handle research, testing, and the demo script.',
        extracted_at: HACKATHON_DEMO_CREATED_AT,
        derived_node_ids: ['harborhelp_team_constraint', 'harborhelp_delivery_plan'],
        processing_status: 'completed',
        origin: 'user',
        extraction_summary: 'Three people have ten days, so the first release needs one narrow workflow.',
      },
      {
        id: 'hackathon_partner_interviews',
        filename: 'shelter-interviews.txt',
        type: 'text',
        content: 'Shelter coordinators need to know quantity, allergens, pickup deadline, and whether a driver is confirmed. They do not want a new account for every one-off donation. A coordinator said a simple text link could be enough for the first pilot.',
        extracted_at: HACKATHON_DEMO_CREATED_AT,
        derived_node_ids: ['harborhelp_shelter_needs', 'harborhelp_account_assumption', 'harborhelp_pilot_contact'],
        processing_status: 'completed',
        origin: 'user',
        extraction_summary: 'Shelters prioritize food safety and a low-friction claim flow over a full account system.',
      },
      {
        id: 'hackathon_judging_rubric',
        filename: 'judging-rubric.pdf',
        type: 'pdf',
        content: 'Judges score demonstrated user value, a credible end-to-end workflow, evidence from real users, and a clear explanation of what could be built next. A polished landing page without a working rescue flow will score poorly.',
        extracted_at: HACKATHON_DEMO_CREATED_AT,
        derived_node_ids: ['harborhelp_judging_bar', 'harborhelp_scope_decision'],
        processing_status: 'completed',
        mime_type: 'application/pdf',
        origin: 'user',
        extraction_summary: 'A working end-to-end rescue flow and user evidence matter more than surface polish.',
      },
      {
        id: 'hackathon_prototype_notes',
        filename: 'prototype-notes.txt',
        type: 'text',
        content: 'The current prototype has restaurant posting, shelter claim, volunteer assignment, and delivery confirmation screens. Matching is manual for now. SMS delivery is not implemented, and the team has not tested the expiry timer with a real coordinator.',
        extracted_at: HACKATHON_DEMO_CREATED_AT,
        derived_node_ids: ['harborhelp_prototype_state', 'harborhelp_sms_risk', 'harborhelp_expiry_test'],
        processing_status: 'completed',
        origin: 'user',
        extraction_summary: 'The core screens exist, but matching, notifications, and expiry behavior are still unvalidated.',
      },
    ],
    nodes: [
      node({
        id: 'harborhelp_goal',
        type: 'GOAL',
        text: 'Build and validate a volunteer coordination tool for same-day food rescue',
        status: 'OPEN',
        confidence: 1,
        impact: 1,
        source_refs: ['hackathon_brief'],
        why_it_matters: ['Defines the user value the hackathon demo must prove.'],
      }),
      node({
        id: 'harborhelp_core_workflow',
        type: 'KNOWN',
        text: 'The demo must show a restaurant post, shelter claim, volunteer pickup, and confirmed delivery',
        status: 'RESOLVED',
        confidence: 0.95,
        impact: 0.9,
        source_refs: ['hackathon_brief'],
      }),
      node({
        id: 'harborhelp_team_constraint',
        type: 'CONSTRAINT',
        text: 'Three people have ten focused build days before the hackathon presentation',
        status: 'RESOLVED',
        confidence: 0.95,
        impact: 0.95,
        source_refs: ['hackathon_team_notes'],
      }),
      node({
        id: 'harborhelp_shelter_needs',
        type: 'KNOWN',
        text: 'Shelter coordinators need quantity, allergens, pickup deadline, and driver confirmation before claiming food',
        status: 'RESOLVED',
        confidence: 0.8,
        impact: 0.85,
        source_refs: ['hackathon_partner_interviews'],
      }),
      node({
        id: 'harborhelp_scope_decision',
        type: 'DECISION',
        text: 'Prioritize one complete rescue workflow over a broad marketplace and polished landing page',
        status: 'RESOLVED',
        confidence: 0.9,
        impact: 0.95,
        source_refs: ['hackathon_judging_rubric', 'hackathon_team_notes'],
      }),
      node({
        id: 'harborhelp_delivery_plan',
        type: 'DECISION',
        text: 'Use manual matching for the first demo and defer automatic matching until after user validation',
        status: 'RESOLVED',
        confidence: 0.8,
        impact: 0.8,
        source_refs: ['hackathon_prototype_notes', 'hackathon_team_notes'],
      }),
      node({
        id: 'harborhelp_expiry_risk',
        type: 'RISK',
        text: 'Food may expire before a shelter confirms a pickup if the deadline and alerts are unclear',
        status: 'OPEN',
        confidence: 0.65,
        impact: 0.9,
        source_refs: ['hackathon_brief', 'hackathon_prototype_notes'],
        why_it_matters: ['A missed pickup undermines the safety and usefulness of the rescue workflow.'],
      }),
      node({
        id: 'harborhelp_sms_risk',
        type: 'RISK',
        text: 'The demo may depend on SMS notifications that are not implemented yet',
        status: 'OPEN',
        confidence: 0.7,
        impact: 0.75,
        source_refs: ['hackathon_prototype_notes'],
        why_it_matters: ['A notification gap could make the volunteer handoff feel incomplete.'],
      }),
      node({
        id: 'harborhelp_account_assumption',
        type: 'ASSUMPTION',
        text: 'Shelters will accept a one-off claim link instead of creating an account',
        status: 'OPEN',
        confidence: 0.45,
        impact: 0.65,
        source_refs: ['hackathon_partner_interviews'],
        why_it_matters: ['This determines whether the first pilot can stay low friction.'],
      }),
      node({
        id: 'harborhelp_pilot_contact',
        type: 'UNKNOWN',
        text: 'Which local shelter coordinator can test the claim and pickup flow before judging?',
        status: 'OPEN',
        confidence: 0.25,
        impact: 0.8,
        priority: 0.78,
        source_refs: ['hackathon_partner_interviews'],
        why_it_matters: ['A real user test is required to validate the workflow before the presentation.'],
      }),
      node({
        id: 'harborhelp_expiry_test',
        type: 'UNKNOWN',
        text: 'What expiry window and reminder timing should HarborHelp use for a same-day donation?',
        status: 'OPEN',
        confidence: 0.3,
        impact: 0.82,
        priority: 0.8,
        source_refs: ['hackathon_prototype_notes', 'hackathon_brief'],
        why_it_matters: ['The team cannot demonstrate a safe handoff without a credible timing rule.'],
      }),
      node({
        id: 'harborhelp_sms_question',
        type: 'UNKNOWN',
        text: 'Can the first demo use a shareable notification link instead of live SMS?',
        status: 'OPEN',
        confidence: 0.35,
        impact: 0.7,
        priority: 0.62,
        source_refs: ['hackathon_prototype_notes'],
        why_it_matters: ['Choosing a simpler notification path protects the ten-day delivery plan.'],
      }),
    ],
    edges: [
      { id: 'harborhelp_edge_goal_scope', source: 'harborhelp_scope_decision', target: 'harborhelp_goal', type: 'supports' },
      { id: 'harborhelp_edge_time_scope', source: 'harborhelp_team_constraint', target: 'harborhelp_scope_decision', type: 'blocks' },
      { id: 'harborhelp_edge_flow_goal', source: 'harborhelp_core_workflow', target: 'harborhelp_goal', type: 'supports' },
      { id: 'harborhelp_edge_shelter_flow', source: 'harborhelp_shelter_needs', target: 'harborhelp_core_workflow', type: 'informs' },
      { id: 'harborhelp_edge_expiry_goal', source: 'harborhelp_expiry_risk', target: 'harborhelp_goal', type: 'blocks' },
      { id: 'harborhelp_edge_sms_scope', source: 'harborhelp_sms_risk', target: 'harborhelp_scope_decision', type: 'blocks' },
      { id: 'harborhelp_edge_account_pilot', source: 'harborhelp_account_assumption', target: 'harborhelp_pilot_contact', type: 'informs' },
      { id: 'harborhelp_edge_pilot_goal', source: 'harborhelp_pilot_contact', target: 'harborhelp_goal', type: 'depends_on' },
      { id: 'harborhelp_edge_expiry_question', source: 'harborhelp_expiry_test', target: 'harborhelp_expiry_risk', type: 'informs' },
      { id: 'harborhelp_edge_sms_question', source: 'harborhelp_sms_question', target: 'harborhelp_sms_risk', type: 'informs' },
      { id: 'harborhelp_edge_delivery_plan', source: 'harborhelp_delivery_plan', target: 'harborhelp_sms_question', type: 'supports' },
    ],
    history: [],
    active_question: null,
  };

  project.active_question = selectTopGap(project, {
    answer_density: 'concise',
    question_frequency: 'moderate',
    challenge_level: 'high',
    evidence_preference: 'research_first',
    brainstorm_style: 'diverge_then_converge',
    uncertainty_style: 'explicit',
    durable_notes: [],
  });
  project.clarity_score = calculateClarityScore(project);
  return project;
}

export const HACKATHON_DEMO_PROJECT = createHackathonDemoProject();
