import type { ClarityEdge, ClarityNode, ContextSource, EdgeType, Project } from '@/types/clarity';
import type { DurableMemory } from '@/types/contextPack';
import { calculateClarityScore, selectTopGap } from '@/lib/prioritization';

/** A deterministic, deliberately rich lab-assistant project used for product demos. */
export const KINTAGEN_DEMO_ID = 'kintagen_scientific_demo';
export const KINTAGEN_DEMO_CREATED_AT = '2026-08-16T09:00:00.000Z';

function node(params: Omit<ClarityNode, 'created_by' | 'created_at' | 'updated_at'>): ClarityNode {
  return { ...params, created_by: 'agent', created_at: KINTAGEN_DEMO_CREATED_AT, updated_at: KINTAGEN_DEMO_CREATED_AT };
}

function source(
  id: string,
  filename: string,
  type: ContextSource['type'],
  content: string,
  derived_node_ids: string[],
  extraction_summary: string,
): ContextSource {
  return {
    id,
    filename,
    type,
    content,
    extracted_at: KINTAGEN_DEMO_CREATED_AT,
    derived_node_ids,
    processing_status: 'completed',
    origin: 'user',
    extraction_summary,
    mime_type: type === 'pdf' ? 'application/pdf' : undefined,
  };
}

export function createKintaGenDemoMemories(): DurableMemory[] {
  return [
    { id: 'kintagen_memory_reproducibility', category: 'current_priorities', text: 'Reproducibility and traceable provenance matter more than a flashy first release.', source: 'seed', source_refs: ['kintagen_fair_notes'], confidence: 0.98, created_at: KINTAGEN_DEMO_CREATED_AT, updated_at: KINTAGEN_DEMO_CREATED_AT, why_remembered: 'Core lab priority for the KintaGen project.' },
    { id: 'kintagen_memory_ip', category: 'custom', text: 'Pre-publication experiments must not leak through public links, shared IPFS gateways, or an immutable log.', source: 'seed', source_refs: ['kintagen_security_review'], confidence: 0.94, created_at: KINTAGEN_DEMO_CREATED_AT, updated_at: KINTAGEN_DEMO_CREATED_AT, why_remembered: 'The research team handles unpublished and potentially patentable results.' },
    { id: 'kintagen_memory_team', category: 'current_priorities', text: 'A five-person team is building a narrow pilot while continuing wet-lab work; async jobs are essential because no one can babysit long analyses.', source: 'seed', source_refs: ['kintagen_team_roadmap'], confidence: 0.92, created_at: KINTAGEN_DEMO_CREATED_AT, updated_at: KINTAGEN_DEMO_CREATED_AT, why_remembered: 'Capacity and lab schedules shape the first release.' },
    { id: 'kintagen_memory_fair', category: 'custom', text: 'The lab prefers FAIR metadata, machine-readable outputs, and a human-readable audit trail for every result.', source: 'seed', source_refs: ['kintagen_fair_notes', 'kintagen_flow_spec'], confidence: 0.96, created_at: KINTAGEN_DEMO_CREATED_AT, updated_at: KINTAGEN_DEMO_CREATED_AT, why_remembered: 'Shared preference for useful, reviewable scientific records.' },
    { id: 'kintagen_memory_meetings', category: 'current_priorities', text: 'The next architecture review should leave the team with one pilot workflow, named owners, and explicit security gates.', source: 'seed', source_refs: ['kintagen_meeting_notes'], confidence: 0.9, created_at: KINTAGEN_DEMO_CREATED_AT, updated_at: KINTAGEN_DEMO_CREATED_AT, why_remembered: 'Seeded meeting objective for the scientific assistant demo.' },
  ];
}

export function createKintaGenDemoProject(): Project {
  const sources: ContextSource[] = [
    source('kintagen_brief', 'kintagen-scientific-ai-assistant-brief.pdf', 'pdf', 'KintaGen is a lab-assistant AI for biology workflows. It turns papers, assay files, spectra, and experiment notes into reproducible, reviewable analysis jobs. Every useful output should have a durable content identifier and a clear explanation of what the system did.', ['kintagen_goal', 'kintagen_workflow', 'kintagen_user_value'], 'Product brief: a reproducible AI assistant for biology and chemistry workflows.'),
    source('kintagen_pain_points', 'lab-pain-points-and-user-interviews.md', 'note', 'Researchers currently pass files through insecure ephemeral links, repeat analyses by hand, and lose context between wet-lab and computational teams. A result can be numerically correct yet impossible for a collaborator to reproduce because the input version, parameters, and software image were not recorded.', ['kintagen_insecure_sharing', 'kintagen_repro_gap', 'kintagen_collaboration_need'], 'Interviews identify insecure sharing, weak reproducibility, and siloed context as the main pains.'),
    source('kintagen_ipfs_architecture', 'ipfs-hot-storage-architecture.md', 'text', 'Large raw files and analysis outputs should be pinned to IPFS through Pinata or Synapse. The application stores CIDs and metadata, not giant blobs in the relational database. Hot pins make active projects available while lifecycle rules can archive cold data later.', ['kintagen_ipfs_decision', 'kintagen_hot_storage', 'kintagen_cid_requirement', 'kintagen_storage_provider_question'], 'Storage design for IPFS CIDs, hot pins, and later archival.'),
    source('kintagen_nostr_security', 'nostr-nip44-identity-and-encryption.md', 'pdf', 'Nostr profiles provide portable researcher identity. NIP-44 encrypted payloads can protect project references and private collaboration messages, but key recovery, revocation, and device loss need an explicit policy before the system handles unpublished work.', ['kintagen_nostr_identity', 'kintagen_encryption_decision', 'kintagen_key_recovery_question', 'kintagen_private_sharing'], 'Nostr/NIP-44 identity and encryption design with unresolved recovery policy.'),
    source('kintagen_flow_spec', 'flow-cadence-provenance-logbook.md', 'text', 'One project NFT can anchor a human-readable workflow story. Each WorkflowStepView records stepNumber, agent, action, resultCID, and timestamp. Cadence should prove ordering and provenance, while sensitive experimental content remains encrypted or off-chain.', ['kintagen_flow_decision', 'kintagen_workflow_steps', 'kintagen_nft_risk', 'kintagen_logbook_question'], 'Flow Cadence logbook proposal for ordered, CID-backed workflow steps.'),
    source('kintagen_queue_architecture', 'async-job-queues-vercel-redis-qstash.md', 'note', 'Analysis jobs run asynchronously through a queue backed by Vercel, Redis, and QStash. Workers must tolerate retries, emit progress, persist partial results, and never create two competing log entries for one job attempt.', ['kintagen_async_decision', 'kintagen_retry_risk', 'kintagen_idempotency_question', 'kintagen_progress_requirement'], 'Queue and worker design for long-running, retryable analysis.'),
    source('kintagen_agent_catalogue', 'scientific-agent-catalogue.md', 'pdf', 'The first catalogue includes ld50-dose for dose-response analysis, gcms-xcms for metabolomics and MoNA matching, nmr1d for Bruker FID deconvolution, a MoNA identifier, and legacy theoretical pipelines. Live R scripts should return estimates, uncertainty, plots, JSON, and input references.', ['kintagen_agent_catalogue', 'kintagen_ld50_agent', 'kintagen_gcms_agent', 'kintagen_nmr_agent', 'kintagen_legacy_scope'], 'Agent catalogue and expected scientific outputs.'),
    source('kintagen_ld50_design', 'ld50-dose-agent-design.md', 'text', 'ld50-dose accepts dose/response data, runs drc_analysis.R through POST /process-job, and returns an LD50 estimate, standard error, 95% confidence interval, diagnostics, and a plot CID. The model family and dose units must be visible in the result.', ['kintagen_ld50_contract', 'kintagen_ld50_uncertainty', 'kintagen_dose_units_question'], 'Dose-response contract and reporting requirements.'),
    source('kintagen_gcms_design', 'gcms-xcms-mona-agent-design.md', 'pdf', 'gcms-xcms processes mzML or CDF files with xcms, identifies peaks, and compares spectra with MoNA. A match is evidence to review, not an automatic compound claim. Library version, thresholds, adduct assumptions, and analyst confirmation must be preserved.', ['kintagen_gcms_contract', 'kintagen_mona_caution', 'kintagen_gcms_validation_question', 'kintagen_library_version_question'], 'GC-MS/xCMS and MoNA pipeline with explicit validation cautions.'),
    source('kintagen_nmr_design', 'nmr1d-bruker-agent-design.md', 'text', 'nmr1d accepts Bruker FID data, performs one-dimensional processing and deconvolution, and returns plots plus structured JSON. Processing settings, phase correction, baseline correction, and manual overrides should be reviewable by a chemist.', ['kintagen_nmr_contract', 'kintagen_nmr_review_requirement', 'kintagen_nmr_settings_question'], 'NMR processing contract and review requirements.'),
    source('kintagen_rag_workflow', 'project-documents-rag-and-metadata.md', 'note', 'Project documents are extracted into metadata, chunked for retrieval, and linked back to their source CID. Retrieval should distinguish the researcher’s notes from machine-derived claims and show the exact excerpt used to explain an answer.', ['kintagen_rag_decision', 'kintagen_metadata_pipeline', 'kintagen_excerpt_requirement', 'kintagen_rag_scope_question'], 'RAG workflow for project documents, provenance, and evidence excerpts.'),
    source('kintagen_fair_notes', 'fair-data-and-reproducibility-checklist.md', 'pdf', 'The pilot should capture sample identifiers, organism or cell line, instrument, units, protocol version, software versions, parameters, operator, timestamps, and links to raw and derived files. FAIR metadata is valuable only if collection does not make the scientist abandon the workflow.', ['kintagen_fair_requirement', 'kintagen_metadata_burden_risk', 'kintagen_schema_question', 'kintagen_reproducibility_goal'], 'FAIR and reproducibility checklist for scientific records.'),
    source('kintagen_team_roadmap', 'team-capacity-and-six-week-roadmap.md', 'text', 'The team has six weeks to demonstrate one credible workflow. Priya owns the R agents, Mateo owns the Vite experience, Lin owns identity and encryption, Noor owns Flow/Cadence, and Sam coordinates lab validation. The roadmap has weekly gates for ingestion, one agent, provenance, and a pilot review.', ['kintagen_team_constraint', 'kintagen_pilot_scope_decision', 'kintagen_owner_map', 'kintagen_latency_question'], 'Six-week plan, owners, and delivery constraints.'),
    source('kintagen_security_review', 'prepublication-security-review.md', 'pdf', 'Unpublished assay data may be patent-relevant. Public IPFS gateways, browser logs, third-party model calls, and immutable chains all require threat modelling. The default should be private encrypted storage and explicit sharing, with redaction before any external model or gateway is used.', ['kintagen_ip_risk', 'kintagen_private_default', 'kintagen_external_model_question', 'kintagen_nft_risk'], 'Security review for unpublished and potentially patentable research.'),
    source('kintagen_partner_lab', 'northshore-metabolomics-lab-pilot-notes.md', 'note', 'The Northshore Metabolomics Lab is willing to review a de-identified GC-MS run. They need a reviewer export that includes peak table, candidate matches, confidence, library version, and a way to comment without changing the original result.', ['kintagen_pilot_partner', 'kintagen_reviewer_export', 'kintagen_gcms_validation_question', 'kintagen_commenting_need'], 'Potential pilot partner and reviewer expectations.'),
    source('kintagen_meeting_notes', 'architecture-review-and-lab-meetings.ics', 'note', 'Upcoming working sessions cover architecture, the Northshore pilot, Flow provenance, GC-MS validation, and the grant reproducibility checklist. The architecture meeting must choose the first end-to-end path and identify which questions require a lab scientist rather than an engineer.', ['kintagen_meeting_commitment', 'kintagen_pilot_meeting', 'kintagen_provenance_meeting', 'kintagen_validation_meeting'], 'Meeting commitments for the KintaGen pilot.'),
    source('kintagen_demo_script', 'scientific-assistant-demo-script.md', 'text', 'The demo should upload one de-identified file, extract metadata, run an analysis asynchronously, show a compact scientific result, pin the output, and append a provenance step. The presenter must explain uncertainty and show how a reviewer can reproduce the result.', ['kintagen_demo_story', 'kintagen_demo_acceptance', 'kintagen_one_path_constraint'], 'Demo narrative and acceptance bar.'),
    source('kintagen_grant_requirements', 'grant-reporting-requirements.pdf', 'pdf', 'The grant report asks for measurable improvements in reproducibility, time-to-review, and safe collaboration. Reported metrics must distinguish automation time from scientist review time and cannot claim biological validity from a software match alone.', ['kintagen_metrics_requirement', 'kintagen_claim_boundary', 'kintagen_latency_question'], 'Grant metrics and scientific-claim boundaries.'),
  ];

  const nodes: ClarityNode[] = [
    node({ id: 'kintagen_goal', type: 'GOAL', text: 'Create KintaGen, a scientific AI assistant for reproducible biology and chemistry workflows', status: 'OPEN', confidence: 1, impact: 1, source_refs: ['kintagen_brief'], why_it_matters: ['This is the project outcome every architecture and agent choice must serve.'] }),
    node({ id: 'kintagen_user_value', type: 'KNOWN', text: 'Researchers need one reviewable path from raw experiment files to explainable, provenance-linked results', status: 'RESOLVED', confidence: 0.93, impact: 0.95, source_refs: ['kintagen_brief', 'kintagen_pain_points'] }),
    node({ id: 'kintagen_workflow', type: 'KNOWN', text: 'The pilot workflow is upload, metadata extraction, asynchronous analysis, review, IPFS pinning, and a provenance entry', status: 'RESOLVED', confidence: 0.9, impact: 0.95, source_refs: ['kintagen_brief', 'kintagen_demo_script'] }),
    node({ id: 'kintagen_reproducibility_goal', type: 'GOAL', text: 'Make every result reproducible from the input CID, software version, parameters, and reviewer-visible history', status: 'OPEN', confidence: 0.95, impact: 0.98, source_refs: ['kintagen_fair_notes'] }),
    node({ id: 'kintagen_insecure_sharing', type: 'RISK', text: 'Ephemeral file links and copied spreadsheets can expose unpublished data and lose analysis context', status: 'OPEN', confidence: 0.85, impact: 0.9, source_refs: ['kintagen_pain_points'], why_it_matters: ['This is the security and collaboration problem the product must improve.'] }),
    node({ id: 'kintagen_repro_gap', type: 'RISK', text: 'A scientifically plausible result may not be reproducible when inputs, parameters, and software versions are missing', status: 'OPEN', confidence: 0.9, impact: 0.95, source_refs: ['kintagen_pain_points'] }),
    node({ id: 'kintagen_collaboration_need', type: 'KNOWN', text: 'Wet-lab scientists and computational reviewers need shared context without overwriting the original result', status: 'RESOLVED', confidence: 0.82, impact: 0.86, source_refs: ['kintagen_pain_points', 'kintagen_partner_lab'] }),
    node({ id: 'kintagen_team_constraint', type: 'CONSTRAINT', text: 'Five people have six weeks and must keep the pilot narrow while continuing lab work', status: 'RESOLVED', confidence: 0.92, impact: 0.94, source_refs: ['kintagen_team_roadmap'] }),
    node({ id: 'kintagen_one_path_constraint', type: 'CONSTRAINT', text: 'The first demo should prove one complete workflow instead of partially integrating every agent', status: 'RESOLVED', confidence: 0.9, impact: 0.9, source_refs: ['kintagen_demo_script', 'kintagen_team_roadmap'] }),
    node({ id: 'kintagen_ipfs_decision', type: 'DECISION', text: 'Store large raw files and outputs by content identifier, with hot pins for active projects', status: 'RESOLVED', confidence: 0.88, impact: 0.9, source_refs: ['kintagen_ipfs_architecture'] }),
    node({ id: 'kintagen_hot_storage', type: 'KNOWN', text: 'Pinata and Synapse are candidate services for keeping active IPFS content available', status: 'RESOLVED', confidence: 0.9, impact: 0.75, source_refs: ['kintagen_ipfs_architecture'] }),
    node({ id: 'kintagen_cid_requirement', type: 'CONSTRAINT', text: 'Every raw input, derived result, plot, and reviewer export needs a stable CID or equivalent content reference', status: 'RESOLVED', confidence: 0.93, impact: 0.92, source_refs: ['kintagen_ipfs_architecture', 'kintagen_flow_spec'] }),
    node({ id: 'kintagen_storage_provider_question', type: 'UNKNOWN', text: 'Should Pinata or Synapse be the primary hot-storage provider for the six-week pilot?', status: 'OPEN', confidence: 0.35, impact: 0.78, priority: 0.78, source_refs: ['kintagen_ipfs_architecture'], why_it_matters: ['Provider choice affects deployment credentials, pin monitoring, cost, and recovery procedures.'] }),
    node({ id: 'kintagen_nostr_identity', type: 'DECISION', text: 'Use portable Nostr profiles to identify researchers and collaborators across projects', status: 'RESOLVED', confidence: 0.78, impact: 0.78, source_refs: ['kintagen_nostr_security'] }),
    node({ id: 'kintagen_encryption_decision', type: 'DECISION', text: 'Use NIP-44 encryption for private project references and collaboration messages', status: 'RESOLVED', confidence: 0.8, impact: 0.94, source_refs: ['kintagen_nostr_security'] }),
    node({ id: 'kintagen_key_recovery_question', type: 'UNKNOWN', text: 'How should a lab recover encrypted KintaGen data after a lost device or rotated Nostr key?', status: 'OPEN', confidence: 0.25, impact: 0.94, priority: 0.9, source_refs: ['kintagen_nostr_security'], why_it_matters: ['Without recovery, encryption can turn a device loss into permanent loss of an experiment record.'] }),
    node({ id: 'kintagen_private_sharing', type: 'CONSTRAINT', text: 'Sharing must be explicit, revocable where possible, and private by default for unpublished work', status: 'RESOLVED', confidence: 0.9, impact: 0.98, source_refs: ['kintagen_nostr_security', 'kintagen_security_review'] }),
    node({ id: 'kintagen_flow_decision', type: 'DECISION', text: 'Use a Flow Cadence project logbook to record ordered workflow steps and result CIDs', status: 'RESOLVED', confidence: 0.77, impact: 0.84, source_refs: ['kintagen_flow_spec'] }),
    node({ id: 'kintagen_workflow_steps', type: 'KNOWN', text: 'A log entry contains step number, agent, action, result CID, and timestamp', status: 'RESOLVED', confidence: 0.92, impact: 0.82, source_refs: ['kintagen_flow_spec'] }),
    node({ id: 'kintagen_nft_risk', type: 'RISK', text: 'An immutable NFT story could expose sensitive metadata or make deletion promises impossible', status: 'OPEN', confidence: 0.72, impact: 0.92, source_refs: ['kintagen_flow_spec', 'kintagen_security_review'], why_it_matters: ['Provenance must not accidentally become a publication channel.'] }),
    node({ id: 'kintagen_logbook_question', type: 'UNKNOWN', text: 'Which fields may safely appear in the Flow logbook for pre-publication experiments?', status: 'OPEN', confidence: 0.3, impact: 0.9, priority: 0.84, source_refs: ['kintagen_flow_spec', 'kintagen_security_review'], why_it_matters: ['This defines the boundary between useful auditability and data leakage.'] }),
    node({ id: 'kintagen_async_decision', type: 'DECISION', text: 'Run long analyses asynchronously through a retryable Vercel, Redis, and QStash queue', status: 'RESOLVED', confidence: 0.9, impact: 0.93, source_refs: ['kintagen_queue_architecture'] }),
    node({ id: 'kintagen_retry_risk', type: 'RISK', text: 'Retries can duplicate scientific outputs or provenance entries when a worker times out after writing partial state', status: 'OPEN', confidence: 0.75, impact: 0.86, source_refs: ['kintagen_queue_architecture'] }),
    node({ id: 'kintagen_idempotency_question', type: 'UNKNOWN', text: 'What idempotency key and retry policy will make repeated analysis jobs safe?', status: 'OPEN', confidence: 0.28, impact: 0.88, priority: 0.82, source_refs: ['kintagen_queue_architecture'], why_it_matters: ['A duplicate or missing result would undermine trust in automated analysis.'] }),
    node({ id: 'kintagen_progress_requirement', type: 'KNOWN', text: 'Workers must show progress, preserve partial results, and distinguish failed, cancelled, and completed jobs', status: 'RESOLVED', confidence: 0.83, impact: 0.8, source_refs: ['kintagen_queue_architecture'] }),
    node({ id: 'kintagen_agent_catalogue', type: 'KNOWN', text: 'The catalogue includes ld50-dose, gcms-xcms, nmr1d, MoNA Identifier, and legacy theoretical pipelines', status: 'RESOLVED', confidence: 0.93, impact: 0.75, source_refs: ['kintagen_agent_catalogue'] }),
    node({ id: 'kintagen_ld50_agent', type: 'KNOWN', text: 'ld50-dose returns an estimate, standard error, 95% confidence interval, diagnostics, and a plot', status: 'RESOLVED', confidence: 0.88, impact: 0.72, source_refs: ['kintagen_agent_catalogue', 'kintagen_ld50_design'] }),
    node({ id: 'kintagen_ld50_contract', type: 'CONSTRAINT', text: 'Dose-response results must show model family, dose units, sample count, and uncertainty beside the estimate', status: 'RESOLVED', confidence: 0.84, impact: 0.82, source_refs: ['kintagen_ld50_design'] }),
    node({ id: 'kintagen_ld50_uncertainty', type: 'RISK', text: 'A single LD50 number without diagnostics could be mistaken for biological certainty', status: 'OPEN', confidence: 0.72, impact: 0.8, source_refs: ['kintagen_ld50_design'] }),
    node({ id: 'kintagen_dose_units_question', type: 'UNKNOWN', text: 'Which dose units and model defaults should KintaGen require before running ld50-dose?', status: 'OPEN', confidence: 0.32, impact: 0.68, priority: 0.62, source_refs: ['kintagen_ld50_design'], why_it_matters: ['Unit ambiguity can make an apparently precise dose-response result misleading.'] }),
    node({ id: 'kintagen_gcms_agent', type: 'KNOWN', text: 'gcms-xcms detects peaks in mzML or CDF data and compares spectra with MoNA', status: 'RESOLVED', confidence: 0.9, impact: 0.84, source_refs: ['kintagen_agent_catalogue', 'kintagen_gcms_design'] }),
    node({ id: 'kintagen_gcms_contract', type: 'CONSTRAINT', text: 'GC-MS output must preserve peak thresholds, adduct assumptions, library version, and candidate match scores', status: 'RESOLVED', confidence: 0.88, impact: 0.9, source_refs: ['kintagen_gcms_design'] }),
    node({ id: 'kintagen_mona_caution', type: 'RISK', text: 'A MoNA match is a candidate identification, not an automatic compound claim', status: 'OPEN', confidence: 0.92, impact: 0.96, source_refs: ['kintagen_gcms_design', 'kintagen_grant_requirements'] }),
    node({ id: 'kintagen_gcms_validation_question', type: 'UNKNOWN', text: 'Who will validate the first GC-MS and MoNA results before they are shown to the pilot lab?', status: 'OPEN', confidence: 0.3, impact: 0.92, priority: 0.88, source_refs: ['kintagen_gcms_design', 'kintagen_partner_lab'], why_it_matters: ['A domain reviewer is needed before a library match becomes part of a scientific decision.'] }),
    node({ id: 'kintagen_library_version_question', type: 'UNKNOWN', text: 'Which MoNA library snapshot should be pinned for reproducible GC-MS comparisons?', status: 'OPEN', confidence: 0.34, impact: 0.76, priority: 0.66, source_refs: ['kintagen_gcms_design'], why_it_matters: ['Library updates can change candidate matches between runs.'] }),
    node({ id: 'kintagen_nmr_agent', type: 'KNOWN', text: 'nmr1d processes Bruker FID data and returns plots plus structured deconvolution JSON', status: 'RESOLVED', confidence: 0.86, impact: 0.76, source_refs: ['kintagen_agent_catalogue', 'kintagen_nmr_design'] }),
    node({ id: 'kintagen_nmr_contract', type: 'CONSTRAINT', text: 'NMR results must expose phase, baseline, deconvolution, and manual override settings', status: 'RESOLVED', confidence: 0.84, impact: 0.78, source_refs: ['kintagen_nmr_design'] }),
    node({ id: 'kintagen_nmr_review_requirement', type: 'KNOWN', text: 'A chemist should be able to review and comment on NMR processing before acceptance', status: 'RESOLVED', confidence: 0.82, impact: 0.82, source_refs: ['kintagen_nmr_design', 'kintagen_partner_lab'] }),
    node({ id: 'kintagen_nmr_settings_question', type: 'UNKNOWN', text: 'Which NMR processing settings must be editable in the first pilot review screen?', status: 'OPEN', confidence: 0.35, impact: 0.62, priority: 0.55, source_refs: ['kintagen_nmr_design'], why_it_matters: ['Exposing every setting would slow delivery; hiding the wrong one reduces scientific reviewability.'] }),
    node({ id: 'kintagen_rag_decision', type: 'DECISION', text: 'Use project-scoped retrieval to explain results from documents, notes, and prior workflow steps', status: 'RESOLVED', confidence: 0.9, impact: 0.88, source_refs: ['kintagen_rag_workflow'] }),
    node({ id: 'kintagen_metadata_pipeline', type: 'KNOWN', text: 'Document extraction stores machine-readable metadata and links every excerpt back to its source CID', status: 'RESOLVED', confidence: 0.87, impact: 0.86, source_refs: ['kintagen_rag_workflow'] }),
    node({ id: 'kintagen_excerpt_requirement', type: 'CONSTRAINT', text: 'Explanations must distinguish researcher notes from machine-derived claims and show the exact supporting excerpt', status: 'RESOLVED', confidence: 0.9, impact: 0.88, source_refs: ['kintagen_rag_workflow'] }),
    node({ id: 'kintagen_rag_scope_question', type: 'UNKNOWN', text: 'Should retrieval include only the active experiment or also the lab notebook history for a project?', status: 'OPEN', confidence: 0.35, impact: 0.72, priority: 0.6, source_refs: ['kintagen_rag_workflow'], why_it_matters: ['Scope changes both answer quality and the chance of exposing unrelated unpublished work.'] }),
    node({ id: 'kintagen_fair_requirement', type: 'CONSTRAINT', text: 'FAIR metadata should capture sample, instrument, units, protocol, software, parameters, operator, and timestamps', status: 'RESOLVED', confidence: 0.95, impact: 0.94, source_refs: ['kintagen_fair_notes'] }),
    node({ id: 'kintagen_metadata_burden_risk', type: 'RISK', text: 'Too much mandatory metadata entry could make scientists abandon the assistant during a busy experiment', status: 'OPEN', confidence: 0.7, impact: 0.78, source_refs: ['kintagen_fair_notes'] }),
    node({ id: 'kintagen_schema_question', type: 'UNKNOWN', text: 'Which minimum metadata schema is enough for the first FAIR-compliant pilot?', status: 'OPEN', confidence: 0.3, impact: 0.86, priority: 0.8, source_refs: ['kintagen_fair_notes'], why_it_matters: ['The schema controls ingestion effort, reproducibility, and whether different agents can share inputs.'] }),
    node({ id: 'kintagen_team_constraint_owners', type: 'KNOWN', text: 'Priya owns R agents, Mateo owns the Vite app, Lin owns Nostr security, Noor owns Cadence, and Sam coordinates lab validation', status: 'RESOLVED', confidence: 0.94, impact: 0.75, source_refs: ['kintagen_team_roadmap'] }),
    node({ id: 'kintagen_pilot_scope_decision', type: 'DECISION', text: 'Pilot one de-identified GC-MS workflow with a reviewable export before adding all agents', status: 'RESOLVED', confidence: 0.79, impact: 0.96, source_refs: ['kintagen_team_roadmap', 'kintagen_partner_lab'] }),
    node({ id: 'kintagen_pilot_partner', type: 'KNOWN', text: 'Northshore Metabolomics Lab may review a de-identified GC-MS run', status: 'RESOLVED', confidence: 0.66, impact: 0.9, source_refs: ['kintagen_partner_lab'] }),
    node({ id: 'kintagen_reviewer_export', type: 'KNOWN', text: 'Pilot reviewers need peak table, candidate matches, confidence, library version, and comments without changing the original result', status: 'RESOLVED', confidence: 0.83, impact: 0.88, source_refs: ['kintagen_partner_lab'] }),
    node({ id: 'kintagen_commenting_need', type: 'NEXT_ACTION', text: 'Prototype a reviewer export and comment thread for one de-identified GC-MS run', status: 'OPEN', confidence: 0.7, impact: 0.82, source_refs: ['kintagen_partner_lab'] }),
    node({ id: 'kintagen_latency_question', type: 'UNKNOWN', text: 'What end-to-end latency is acceptable for a GC-MS pilot analysis and human review?', status: 'OPEN', confidence: 0.3, impact: 0.78, priority: 0.7, source_refs: ['kintagen_team_roadmap', 'kintagen_grant_requirements'], why_it_matters: ['Latency is a grant metric and determines whether the workflow fits a real lab schedule.'] }),
    node({ id: 'kintagen_ip_risk', type: 'RISK', text: 'Public gateways, browser logs, third-party models, and immutable chains could expose patent-relevant data', status: 'OPEN', confidence: 0.82, impact: 0.98, source_refs: ['kintagen_security_review'] }),
    node({ id: 'kintagen_private_default', type: 'DECISION', text: 'Default to private encrypted storage and require explicit redaction before external model or gateway use', status: 'RESOLVED', confidence: 0.85, impact: 0.98, source_refs: ['kintagen_security_review'] }),
    node({ id: 'kintagen_external_model_question', type: 'UNKNOWN', text: 'Which documents, if any, may be sent to an external model after redaction?', status: 'OPEN', confidence: 0.3, impact: 0.88, priority: 0.76, source_refs: ['kintagen_security_review'], why_it_matters: ['The answer sets the boundary for useful AI assistance without leaking research IP.'] }),
    node({ id: 'kintagen_meeting_commitment', type: 'NEXT_ACTION', text: 'Use the architecture review to choose the first workflow, owners, security gates, and success metrics', status: 'OPEN', confidence: 0.82, impact: 0.9, source_refs: ['kintagen_meeting_notes'] }),
    node({ id: 'kintagen_pilot_meeting', type: 'NEXT_ACTION', text: 'Confirm the Northshore pilot data, reviewer, and de-identification checklist', status: 'OPEN', confidence: 0.7, impact: 0.86, source_refs: ['kintagen_meeting_notes', 'kintagen_partner_lab'] }),
    node({ id: 'kintagen_provenance_meeting', type: 'NEXT_ACTION', text: 'Review which workflow fields can be written to the Flow provenance logbook', status: 'OPEN', confidence: 0.68, impact: 0.82, source_refs: ['kintagen_meeting_notes', 'kintagen_flow_spec'] }),
    node({ id: 'kintagen_validation_meeting', type: 'NEXT_ACTION', text: 'Have a domain scientist review the first xCMS peak and MoNA match export', status: 'OPEN', confidence: 0.68, impact: 0.92, source_refs: ['kintagen_meeting_notes', 'kintagen_partner_lab'] }),
    node({ id: 'kintagen_demo_story', type: 'KNOWN', text: 'The demo story is upload, extract, run, review uncertainty, pin output, and append one provenance step', status: 'RESOLVED', confidence: 0.9, impact: 0.9, source_refs: ['kintagen_demo_script'] }),
    node({ id: 'kintagen_demo_acceptance', type: 'CONSTRAINT', text: 'The presenter must show how a reviewer can reproduce the result and avoid overstating a library match', status: 'RESOLVED', confidence: 0.88, impact: 0.9, source_refs: ['kintagen_demo_script', 'kintagen_grant_requirements'] }),
    node({ id: 'kintagen_metrics_requirement', type: 'CONSTRAINT', text: 'Success metrics separate automation time from scientist review time and track reproducibility improvements', status: 'RESOLVED', confidence: 0.83, impact: 0.72, source_refs: ['kintagen_grant_requirements'] }),
    node({ id: 'kintagen_claim_boundary', type: 'CONSTRAINT', text: 'Software output may suggest a candidate compound but cannot claim biological validity without expert review', status: 'RESOLVED', confidence: 0.94, impact: 0.94, source_refs: ['kintagen_grant_requirements'] }),
  ];

  const edgePairs: Array<[string, string, EdgeType]> = [
    ['kintagen_workflow', 'kintagen_goal', 'supports'], ['kintagen_reproducibility_goal', 'kintagen_goal', 'supports'], ['kintagen_user_value', 'kintagen_goal', 'supports'],
    ['kintagen_insecure_sharing', 'kintagen_goal', 'blocks'], ['kintagen_repro_gap', 'kintagen_reproducibility_goal', 'blocks'], ['kintagen_team_constraint', 'kintagen_one_path_constraint', 'supports'],
    ['kintagen_one_path_constraint', 'kintagen_pilot_scope_decision', 'supports'], ['kintagen_ipfs_decision', 'kintagen_cid_requirement', 'supports'], ['kintagen_storage_provider_question', 'kintagen_ipfs_decision', 'informs'],
    ['kintagen_encryption_decision', 'kintagen_private_sharing', 'supports'], ['kintagen_key_recovery_question', 'kintagen_encryption_decision', 'blocks'], ['kintagen_private_sharing', 'kintagen_ip_risk', 'blocks'],
    ['kintagen_flow_decision', 'kintagen_workflow_steps', 'supports'], ['kintagen_logbook_question', 'kintagen_nft_risk', 'informs'], ['kintagen_nft_risk', 'kintagen_flow_decision', 'blocks'],
    ['kintagen_async_decision', 'kintagen_progress_requirement', 'supports'], ['kintagen_idempotency_question', 'kintagen_retry_risk', 'informs'], ['kintagen_retry_risk', 'kintagen_async_decision', 'blocks'],
    ['kintagen_pilot_scope_decision', 'kintagen_gcms_agent', 'supports'], ['kintagen_ld50_agent', 'kintagen_agent_catalogue', 'derived_from'], ['kintagen_gcms_agent', 'kintagen_agent_catalogue', 'derived_from'],
    ['kintagen_nmr_agent', 'kintagen_agent_catalogue', 'derived_from'], ['kintagen_dose_units_question', 'kintagen_ld50_contract', 'informs'], ['kintagen_ld50_uncertainty', 'kintagen_ld50_agent', 'blocks'],
    ['kintagen_gcms_contract', 'kintagen_gcms_agent', 'supports'], ['kintagen_mona_caution', 'kintagen_gcms_agent', 'blocks'], ['kintagen_gcms_validation_question', 'kintagen_mona_caution', 'informs'],
    ['kintagen_library_version_question', 'kintagen_gcms_contract', 'informs'], ['kintagen_nmr_contract', 'kintagen_nmr_agent', 'supports'], ['kintagen_nmr_review_requirement', 'kintagen_nmr_agent', 'supports'],
    ['kintagen_nmr_settings_question', 'kintagen_nmr_contract', 'informs'], ['kintagen_rag_decision', 'kintagen_metadata_pipeline', 'supports'], ['kintagen_excerpt_requirement', 'kintagen_rag_decision', 'supports'],
    ['kintagen_rag_scope_question', 'kintagen_rag_decision', 'informs'], ['kintagen_fair_requirement', 'kintagen_reproducibility_goal', 'supports'], ['kintagen_schema_question', 'kintagen_fair_requirement', 'informs'],
    ['kintagen_metadata_burden_risk', 'kintagen_fair_requirement', 'blocks'], ['kintagen_pilot_partner', 'kintagen_pilot_scope_decision', 'supports'], ['kintagen_reviewer_export', 'kintagen_pilot_scope_decision', 'supports'],
    ['kintagen_commenting_need', 'kintagen_reviewer_export', 'depends_on'], ['kintagen_latency_question', 'kintagen_pilot_scope_decision', 'informs'], ['kintagen_ip_risk', 'kintagen_private_default', 'supports'],
    ['kintagen_external_model_question', 'kintagen_private_default', 'informs'], ['kintagen_meeting_commitment', 'kintagen_pilot_scope_decision', 'supports'], ['kintagen_pilot_meeting', 'kintagen_pilot_partner', 'depends_on'],
    ['kintagen_provenance_meeting', 'kintagen_logbook_question', 'depends_on'], ['kintagen_validation_meeting', 'kintagen_gcms_validation_question', 'depends_on'], ['kintagen_demo_story', 'kintagen_workflow', 'supports'],
    ['kintagen_demo_acceptance', 'kintagen_claim_boundary', 'supports'], ['kintagen_metrics_requirement', 'kintagen_goal', 'informs'], ['kintagen_claim_boundary', 'kintagen_mona_caution', 'supports'],
  ];
  const edges: ClarityEdge[] = edgePairs.map(([sourceId, target, type], index) => ({ id: `kintagen_edge_${index + 1}`, source: sourceId, target, type }));
  const project: Project = { id: KINTAGEN_DEMO_ID, title: 'KintaGen — Scientific AI Assistant', goal: 'Create a secure, reproducible AI assistant for biology and chemistry workflows.', status: 'active', deadline: '2026-09-27', one_sentence_context: 'A six-week lab-assistant pilot that turns scientific files into reviewable, provenance-linked analysis results without exposing unpublished research.', clarity_score: 0, created_at: KINTAGEN_DEMO_CREATED_AT, updated_at: KINTAGEN_DEMO_CREATED_AT, sources, nodes, edges, history: [], active_question: null };
  project.active_question = selectTopGap(project, { answer_density: 'detailed', question_frequency: 'moderate', challenge_level: 'high', evidence_preference: 'strict_data', brainstorm_style: 'diverge_then_converge', uncertainty_style: 'explicit', durable_notes: [] });
  project.clarity_score = calculateClarityScore(project);
  return project;
}

export const KINTAGEN_DEMO_PROJECT = createKintaGenDemoProject();
