import { Project, UserMemoryProfile } from '@/types/clarity';
import { calculateClarityScore, selectTopGap } from '@/lib/prioritization';

export const DEMO_USER_ID = 'demo-user';

export const DEFAULT_USER_PROFILE: UserMemoryProfile = {
  answer_density: 'concise',
  question_frequency: 'moderate',
  challenge_level: 'high',
  evidence_preference: 'research_first',
  brainstorm_style: 'diverge_then_converge',
  uncertainty_style: 'explicit',
  durable_notes: [
    'I prefer concise explanations.',
    'Ship Gapswise before expanding the job search.',
  ],
};

const PROJECT_CREATED_AT = '2026-08-10T10:00:00.000Z';

export function createGoldenDemoProject(): Project {
  const project: Project = {
    id: 'hackathon_demo',
    title: 'Gapswise Hackathon Submission',
    goal: 'Ship a winning Collaborative Partner project in 2-3 weeks',
    deadline: '2026-08-31',
    one_sentence_context:
      'A persistent collaborative thinking agent that exposes missing information and guides the user to resolve it.',
    clarity_score: 63,
    created_at: PROJECT_CREATED_AT,
    updated_at: PROJECT_CREATED_AT,
    sources: [
      {
        id: 'src_1',
        filename: 'hackathon-rules.pdf',
        type: 'pdf',
        content:
          'Track: Collaborative Partner. Requirements: Stateful multi-turn dialogue, real-time context retrieval / RAG, persistent memory across sessions, clarifying questions, step-by-step guidance, user feedback capture.',
        extracted_at: '2026-08-10T10:00:00Z',
        derived_node_ids: ['node_known_track'],
        processing_status: 'completed',
        mime_type: 'application/pdf',
        origin: 'user',
        extraction_summary: 'Hackathon track requirements and persistent partner criteria.',
      },
      {
        id: 'src_2',
        filename: 'idea-brainstorm.txt',
        type: 'text',
        content:
          'Idea 1: Universal life OS. Idea 2: Email cleanup agent. Idea 3: Gapswise clarity graph & gap-driven thinking agent. Idea 4: Calendar manager.',
        extracted_at: '2026-08-10T10:15:00Z',
        derived_node_ids: ['node_decision_track'],
        processing_status: 'completed',
        mime_type: 'text/plain',
        origin: 'user',
        extraction_summary: 'Early idea exploration that selected Gapswise as the project direction.',
      },
      {
        id: 'src_3',
        filename: 'arch-sketch.png',
        type: 'image',
        content:
          'System architecture: Next.js Frontend -> Cloud Run API -> Google ADK Agent -> Gemini 3.5 Flash & Firestore DB.',
        extracted_at: '2026-08-10T10:30:00Z',
        derived_node_ids: ['node_known_arch'],
        processing_status: 'completed',
        mime_type: 'image/png',
        origin: 'user',
        extraction_summary: 'Architecture sketch for the Google/Gemini persistence stack.',
      },
      {
        id: 'src_4',
        filename: 'constraint-note.txt',
        type: 'note',
        content: 'Team constraints: 2 developers, 14 days remaining before submission deadline.',
        extracted_at: '2026-08-10T11:00:00Z',
        derived_node_ids: ['node_constraint_time'],
        processing_status: 'completed',
        mime_type: 'text/plain',
        origin: 'user',
        extraction_summary: 'Team size and timeline constraint.',
      },
    ],
    nodes: [
      {
        id: 'node_goal',
        type: 'GOAL',
        text: 'Build and ship a winning Collaborative Partner hackathon project',
        status: 'OPEN',
        confidence: 1,
        impact: 1,
        source_refs: ['src_1'],
        created_by: 'user',
        created_at: '2026-08-10T10:00:00Z',
        updated_at: '2026-08-10T10:00:00Z',
        x: 350,
        y: 80,
      },
      {
        id: 'node_known_track',
        type: 'KNOWN',
        text: 'Track requires stateful multi-turn dialogue, persistent memory, and clarifying questions',
        status: 'RESOLVED',
        confidence: 1,
        impact: 0.9,
        source_refs: ['src_1'],
        created_by: 'agent',
        created_at: '2026-08-10T10:05:00Z',
        updated_at: '2026-08-10T10:05:00Z',
        x: 120,
        y: 180,
      },
      {
        id: 'node_constraint_time',
        type: 'CONSTRAINT',
        text: 'Two developers with 14 days remaining before final deadline',
        status: 'RESOLVED',
        confidence: 1,
        impact: 0.95,
        source_refs: ['src_4'],
        created_by: 'agent',
        created_at: '2026-08-10T11:00:00Z',
        updated_at: '2026-08-10T11:00:00Z',
        x: 580,
        y: 180,
      },
      {
        id: 'node_decision_track',
        type: 'DECISION',
        text: 'Build Gapswise: Find the question that unlocks the next decision',
        status: 'RESOLVED',
        confidence: 0.95,
        impact: 0.95,
        source_refs: ['src_2'],
        created_by: 'user',
        created_at: '2026-08-10T10:20:00Z',
        updated_at: '2026-08-10T10:20:00Z',
        x: 350,
        y: 260,
      },
      {
        id: 'node_assumption_visual',
        type: 'ASSUMPTION',
        text: 'Judges will value an interactive visual Clarity Graph over a generic chatbot interface',
        status: 'OPEN',
        confidence: 0.55,
        impact: 0.85,
        source_refs: ['src_2'],
        created_by: 'agent',
        created_at: '2026-08-10T10:35:00Z',
        updated_at: '2026-08-10T10:35:00Z',
        x: 140,
        y: 360,
      },
      {
        id: 'unknown_target_user',
        type: 'UNKNOWN',
        text: 'Who exactly is the primary target persona and 4-minute demo scenario for Gapswise?',
        status: 'OPEN',
        confidence: 0.18,
        impact: 0.94,
        priority: 0.91,
        source_refs: ['src_2'],
        why_it_matters: [
          'Blocks core demo narrative and onboarding flow',
          'Affects feature scoping for 2-week build horizon',
          'Determines how judges evaluate operational utility',
        ],
        created_by: 'agent',
        created_at: '2026-08-10T10:40:00Z',
        updated_at: '2026-08-10T10:40:00Z',
        x: 560,
        y: 360,
      },
      {
        id: 'unknown_pricing',
        type: 'UNKNOWN',
        text: 'What evidence exists for willingness-to-pay and pricing model strategy?',
        status: 'OPEN',
        confidence: 0.25,
        impact: 0.7,
        priority: 0.68,
        source_refs: [],
        why_it_matters: ['Secondary validation gap for post-hackathon commercialization'],
        created_by: 'agent',
        created_at: '2026-08-10T11:10:00Z',
        updated_at: '2026-08-10T11:10:00Z',
        x: 350,
        y: 480,
      },
      {
        id: 'node_risk_latency',
        type: 'RISK',
        text: 'RAG ingestion and Gemini API call latency could slow down live demo responses',
        status: 'OPEN',
        confidence: 0.4,
        impact: 0.75,
        source_refs: ['src_3'],
        created_by: 'agent',
        created_at: '2026-08-10T11:15:00Z',
        updated_at: '2026-08-10T11:15:00Z',
        x: 120,
        y: 500,
      },
    ],
    edges: [
      { id: 'e1', source: 'node_known_track', target: 'node_goal', type: 'supports' },
      { id: 'e2', source: 'node_constraint_time', target: 'node_goal', type: 'blocks' },
      { id: 'e3', source: 'node_decision_track', target: 'node_goal', type: 'informs' },
      { id: 'e4', source: 'node_assumption_visual', target: 'node_decision_track', type: 'supports' },
      { id: 'e5', source: 'unknown_target_user', target: 'node_decision_track', type: 'blocks' },
      { id: 'e6', source: 'unknown_pricing', target: 'node_decision_track', type: 'depends_on' },
      { id: 'e7', source: 'node_risk_latency', target: 'node_decision_track', type: 'blocks' },
    ],
    history: [],
    active_question: null,
  };

  project.active_question = selectTopGap(project, DEFAULT_USER_PROFILE);
  project.clarity_score = calculateClarityScore(project);
  return project;
}

export const GOLDEN_DEMO_PROJECT = createGoldenDemoProject();
